server:
  port: 8080

kafka:
  producer:
    topic1: topic1
    topic2: topic2

spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
#    producer:
#      acks: all
